spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}

spring.flyway.enabled=${SPRING_FLYWAY_ENABLED:true}
spring.flyway.locations=${SPRING_FLYWAY_LOCATIONS:classpath:db/migration}
