CREATE TABLE tb_usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    perfil VARCHAR(255) NOT NULL,
    CONSTRAINT uk_tb_usuarios_email UNIQUE (email)
);

CREATE TABLE tb_servicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    preco NUMERIC(38, 2) NOT NULL,
    duracao_em_minutos INTEGER NOT NULL
);

CREATE TABLE tb_agendamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataehora TIMESTAMP NOT NULL,
    status VARCHAR(255) NOT NULL,
    forma_de_pagamento VARCHAR(255) NOT NULL,
    cliente_id BIGINT NOT NULL,
    barbeiro_id BIGINT NOT NULL,
    servico_id BIGINT NOT NULL,
    CONSTRAINT fk_agendamentos_cliente FOREIGN KEY (cliente_id) REFERENCES tb_usuarios (id),
    CONSTRAINT fk_agendamentos_barbeiro FOREIGN KEY (barbeiro_id) REFERENCES tb_usuarios (id),
    CONSTRAINT fk_agendamentos_servico FOREIGN KEY (servico_id) REFERENCES tb_servicos (id)
);

CREATE INDEX idx_agendamentos_barbeiro_data ON tb_agendamentos (barbeiro_id, dataehora);
CREATE INDEX idx_agendamentos_cliente ON tb_agendamentos (cliente_id);
CREATE INDEX idx_agendamentos_servico ON tb_agendamentos (servico_id);
